apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: prod-project
  namespace: argocd
spec:
  description: Restricted Project

  sourceRepos:
    - https://github.com/smogalloyubio/Gcp-kS3-Gitops-Pipeline.git

  destinations:
    - namespace: prod
      server: https://kubernetes.default.svc

  clusterResourceWhitelist: []
  
  namespaceResourceWhitelist:
    - group: apps
      kind: Deployment
    - group: v1
      kind: Service