apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bitcoin-prod-app
  namespace: argocd 
spec:
  project: default 


  source:
    repoURL: 'https://github.com/smogalloyubio/Gcp-kS3-Gitops-Pipeline'
    targetRevision: main
    path: production-manifest    


  destination:
    server: 'https://kubernetes.default.svc' 
    namespace: prod                         


  syncPolicy:
    automated:
      prune: true     
    syncOptions:
      - CreateNamespace=true 