apiVersion: v1
kind: Service
metadata:
  name: my-bitcoin-web-application
  namespace: dev
spec:
  selector:
    app: my-bitcoin-web-application
  ports:
    - name: http
      port: 5000
      targetPort: 5000
