apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml  
  - service.yaml 

namespace: stage
replicas:
  - name: my-bitcoin-web-application
    count: 4                      


images:
  - name: rukevweubio/my-bitcoin-web-application
    newName: rukevweubio/my-bitcoin-web-application
    newTag: latest
