name: Build and Deploy Web Application to GCP k3s

on:
  push:
    branches:
      - qa-engineer
    paths:
      - '.github/workflows/Google_cloud_deploy.yaml'
      - 'static/**'
      - 'kustomized/**'
      - 'Dockerfile'

permissions:
  contents: write
  id-token: write 

jobs:
  gitleak-scan-security: 
    name: Run Gitleaks Security Scan
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Gitleak scan 
        run: |
          docker run --rm \
              -v "${{ github.workspace }}:/repo" \
              zricethezav/gitleaks:latest detect \
              --source=/repo \
              --report-format=json \
              --report-path=/repo/gitleaks-report.json \
              --redact \
              --exit-code 0

      - name: Upload Artifact Of Gitleak Scan 
        uses: actions/upload-artifact@v4 
        with: 
          name: gitleak-report
          path: ${{ github.workspace }}/gitleaks-report.json
          if-no-files-found: warn

  Checkov-Terraform:
    name: Checkov Terraform Scan 
    needs: [gitleak-scan-security]
    if: ${{ success() }}
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Checkov Scan
        uses: bridgecrewio/checkov-action@master
        id: checkov
        with:
          directory: ./Terraform
          framework: terraform
          output_format: json
          output_file_path: checkov-terraform-report.json
          download_external_modules: false
          skip_path: '**/.terraform/**'   
          soft_fail: true

      - name: Upload Artifact Of Gitleak Scan 
        uses: actions/upload-artifact@v4 
        with: 
          name: checkov-terraform-report
          path: ${{ github.workspace }}/checkov-terraform-report.json
          if-no-files-found: warn


  Checkov-Dockerfile:
    name: Checkov Dockerfile Scan 
    needs: [gitleak-scan-security]
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Checkov Scan
        uses: bridgecrewio/checkov-action@master
        id: checkov
        with:
          file: ./Dockerfile
          framework: dockerfile
          output_format: json
          output_file_path: checkov-dockerfile-report.json
          download_external_modules: false   
          soft_fail: true

      - name: Upload Artifact Of Checkov Dockerfile Scan 
        uses: actions/upload-artifact@v4 
        with: 
          name: checkov-dockerfile-report 
          path: ${{ github.workspace }}/checkov-dockerfile-report.json
          if-no-files-found: warn


  Checkov-Kubernetes:
    name: Checkov Kubernetes Scan 
    needs: [gitleak-scan-security]
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Checkov Scan
        uses: bridgecrewio/checkov-action@master
        id: checkov
        with:
          directory: ./kustomized 
          framework: kubernetes
          output_format: json
          output_file_path: checkov-kubernetes-report.json
          soft_fail: true

      - name: Upload Artifact Of Checkov Kubernetes Scan 
        uses: actions/upload-artifact@v4 
        with: 
          name: checkov-kubernetes-report
          path: ${{ github.workspace }}/checkov-kubernetes-report.json
          if-no-files-found: warn



  Trivy-Python-Code-Scan:
    name: Trivy Python Code & Dependency Scan
    needs: 
      - gitleak-scan-security
      - Checkov-Kubernetes
      - Checkov-Terraform
      - Checkov-Dockerfile
    if: ${{ success() }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Run Trivy FS Scan for Python Dependencies
        uses: aquasecurity/trivy-action@master 
        with:
          scan-type: 'fs'
          scan-ref: '.' 
          format: 'table'
          exit-code: '0' 
          output: trivy-scan-security-code-report.json 
          severity: 'HIGH,CRITICAL'

      - name: Upload Artifact of trivy dockerfile  Scan 
        uses: actions/upload-artifact@v4 
        with: 
          name: trivy-scan-security-code-report 
          path: ${{ github.workspace }}/trivy-scan-security-code-report.json 
          if-no-files-found: warn
      

  Trivy-Dockerfile-Scan:
    name: Trivy Dockerfile Config Scan
    needs: 
      - gitleak-scan-security
      - Checkov-Kubernetes
      - Checkov-Terraform
      - Checkov-Dockerfile

    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Run Trivy misconfiguration scan on Dockerfile
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'config'
          scan-ref: './Dockerfile' 
          format: 'table'
          exit-code: '0'
          output: dockerfile-trivy-scan-report.json 
          severity: 'HIGH,CRITICAL'

      - name: Upload Artifact of trivy dockerfile  Scan 
        uses: actions/upload-artifact@v4 
        with: 
          name: dockerfile-trivy-scan-report
          path: ${{ github.workspace }}/dockerfile-trivy-scan-report.json
          if-no-files-found: warn

  Linting-Stage_code:
    name: Core Linting Static
    needs:  
      - Checkov-Kubernetes
      - Checkov-Terraform
      - Checkov-Dockerfile
      - Trivy-Python-Code-Scan
      - Trivy-Dockerfile-Scan
      - gitleak-scan-security
    if: ${{ success() }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Run Python Linter (Ruff)
        run: |
          pip install ruff
          ruff check . --exit-zero 

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Lint Frontend Assets
        run: |
          npx eslint "./static/**/*.js" --env browser > ./static-reports/javascript-lint.txt || true


      - name: Upload Static Folder Lint Reports
        uses: actions/upload-artifact@v4
        with:
          name: static-folder-lint-results
          path: ./static-reports/javascript-lint.txt 

  Linting-source-code:
    name: Core Linting Checks Source
    needs:  
      - Checkov-Kubernetes
      - Checkov-Terraform
      - Checkov-Dockerfile
      - Trivy-Python-Code-Scan
      - Trivy-Dockerfile-Scan
      - gitleak-scan-security
    if: ${{ success() }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Run Python Linter (Ruff)
        run: |
          pip install ruff
          ruff check . --exit-zero 

      - name: Set up Node.js
        uses: actions/setup-node@v4
        continue-on-error: true
        with:
          node-version: "20"
      - name: Lint Frontend Assets
        run: |
          npx stylelint "./static/**/*.css" > ./static-reports/css-lint.txt || true
      

      - name: Upload Static Folder Lint Reports
        uses: actions/upload-artifact@v4
        with:
          name: static-folder-lint-results
          path: ./static-reports/* 

  building-docker-image:
    name: building Docker Container Image 
    runs-on: ubuntu-latest 
    if: ${{success()}}
    needs: 
      - Linting-source-code
      - Linting-Stage_code
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3  

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Web Application Image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: false 
          load: true 
          tags: |
            rukevweubio/my-bitcoin-web-application:${{ github.sha }}
            rukevweubio/my-bitcoin-web-application:latest
          cache-from: type=gha 
          cache-to: type=gha,mode=max

      - name: Run Trivy Security Scan (Frontend)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'rukevweubio/my-bitcoin-web-application:latest'
          format: 'table'
          exit-code: '0'   
          severity: 'CRITICAL,HIGH'


      - name: Run Trivy Security Scan (Frontend)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'rukevweubio/my-bitcoin-web-application:${{ github.sha }}'
          format: 'table'
          exit-code: '0'   
          severity: 'CRITICAL,HIGH'
      
      - name: Archive Docker Image
        run: |
          docker save rukevweubio/my-bitcoin-web-application:${{ github.sha }} -o /tmp/my-bitcoin-web-application.tar

      - name: Upload Docker Image Artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-image-artifact-github-sha 
          path: /tmp/my-bitcoin-web-application.tar
          retention-days: 2


      - name: Generate Frontend Source SBOM
        uses: anchore/sbom-action@v0.18.0
        with:
          path: . 
          format: spdx-json
          output-file: frontend-source-sbom.spdx.json
          upload-artifact: true

      
      - name: Generate Frontend Image SBOM
        uses: anchore/sbom-action@v0.18.0
        with:
          image: rukevweubio/my-bitcoin-web-application:${{ github.sha }}
          format: spdx-json
          output-file: docker-image-sbom.spdx.json
          upload-artifact: true

      - name: Push Images to Docker Hub
        run: |
             docker push rukevweubio/my-bitcoin-web-application:${{ github.sha }}
             docker push  rukevweubio/my-bitcoin-web-application:latest


  Deploy-To-Dev:
    name: Scan Manifests & Deploy to Dev Namespace
    needs: [building-docker-image] 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Update Manifest Image Tag
        run: |
          cd ./kustomized
          # Replaces the placeholder image tag with the unique Git Commit SHA
          #sed -i "s|newTag:.*|newTag: qabuild-${{ github.sha }}|g" kustomization.yaml || true
          # Or if using a standard deployment file:
           sed -i "s|image: rukevweubio/my-bitcoin-web-application:.*|image: rukevweubio/my-bitcoin-web-application:${{ github.sha }}|g" deployment.yaml

     
      - name: Run Trivy Config Scan on Manifests
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'config' 
          scan-ref: './kustomized'
          format: 'table'
          exit-code: '0' 
          severity: 'HIGH,CRITICAL'

   
      - name: Setup Kubernetes Context
        uses: azure/k8s-set-context@v4
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG_DEV }}

      - name: Setup Kustomize
        uses: imranismail/setup-kustomize@v2
        with:
          kustomize-version: "v5.4.2"
      
      - name: Update Manifest Image Tag via Kustomize
        run: |
          cd ./kustomized
          kustomize edit set image rukevweubio/my-bitcoin-web-application=rukevweubio/my-bitcoin-web-application:latest 
    
      - name: Deploy to Dev Namespace
        run: |
         
           kubectl apply -k ./kustomized --namespace=dev
          
       
           kubectl rollout status deployment/my-bitcoin-web-application --namespace=dev --timeout=60s
      