name: Build and Deploy Web Application to GCP k3s

on:
  push:
    branches:
      - qa-engineer
    paths:
      - '.github/workflows/Google_cloud_deploy.yaml'
      - 'static/**'
      - 'kustomized/**'
      - 'Dockerfile'

permissions:
  contents: write
  id-token: write 

jobs:
  gitleak-scan-security: 
    name: Run Gitleaks Security Scan
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Gitleak scan 
        run: |
          docker run --rm \
              -v "${{ github.workspace }}:/repo" \
              zricethezav/gitleaks:latest detect \
              --source=/repo \
              --report-format=json \
              --report-path=/repo/gitleaks-report.json \
              --redact \
              --exit-code 0

      - name: Upload Artifact Of Gitleak Scan 
        uses: actions/upload-artifact@v4 
        with: 
          name: gitleak-report
          path: ${{ github.workspace }}/gitleaks-report.json
          if-no-files-found: warn

  Checkov-Terraform:
    name: Checkov Terraform Scan 
    needs: [gitleak-scan-security]
    if: ${{ success() }}
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Checkov Scan
        uses: bridgecrewio/checkov-action@master
        id: checkov
        with:
          directory: ./Terraform
          framework: terraform
          output_format: json
          output_file_path: checkov-terraform-report.json
          download_external_modules: false
          skip_path: '**/.terraform/**'   
          soft_fail: true

      - name: Upload Artifact Of Gitleak Scan 
        uses: actions/upload-artifact@v4 
        with: 
          name: checkov-terraform-report
          path: ${{ github.workspace }}/checkov-terraform-report.json
          if-no-files-found: warn


  Checkov-Dcokerfile:
    name: Checkov Dockerfile Scan 
    needs: [gitleak-scan-security]
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Checkov Scan
        uses: bridgecrewio/checkov-action@master
        id: checkov
        with:
          file: ./Dockerfile
          framework: dockerfile
          output_format: json
          output_file_path: checkov-dockerfile-report.json
          download_external_modules: false   
          soft_fail: true

      - name: Upload Artifact Of Checkov Dockerfile Scan 
        uses: actions/upload-artifact@v4 
        with: 
          name: checkov-dockerfile-report 
          path: ${{ github.workspace }}/checkov-dockerfile-report.json
          if-no-files-found: warn


  Checkov-Kubernetes:
    name: Checkov Kubernetes Scan 
    needs: [gitleak-scan-security]
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Checkov Scan
        uses: bridgecrewio/checkov-action@master
        id: checkov
        with:
          directory: ./kustomized 
          framework: kubernetes
          output_format: json
          output_file_path: checkov-kubernetes-report.json
          soft_fail: true

      - name: Upload Artifact Of Checkov Kubernetes Scan 
        uses: actions/upload-artifact@v4 
        with: 
          name: checkov-kubernetes-report
          path: ${{ github.workspace }}/checkov-kubernetes-report.json
          if-no-files-found: warn



  Trivy-Python-Code-Scan:
    name: Trivy Python Code & Dependency Scan
    needs: 
      - gitleak-scan-security
      - Checkov-Kubernetes
      - Checkov-Terraform
      - Checkov-Dcokerfile
    if: ${{ success() }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Run Trivy FS Scan for Python Dependencies
        uses: aquasecurity/trivy-action@master 
        with:
          scan-type: 'fs'
          scan-ref: '.' 
          format: 'table'
          exit-code: '0' 
          severity: 'HIGH,CRITICAL'

  Trivy-Dockerfile-Scan:
    name: Trivy Dockerfile Config Scan
    needs: 
      - gitleak-scan-security
      - Checkov-Kubernetes
      - Checkov-Terraform
      - Checkov-Dcokerfile

    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Run Trivy misconfiguration scan on Dockerfile
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'config'
          scan-ref: './Dockerfile' 
          format: 'table'
          exit-code: '0'
          severity: 'HIGH,CRITICAL'